version: "3"
services:
  selenium:
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 4444:4444
  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
    volumes:
      - /dev/shm:/dev/shm